
import type { Location } from './types';

export const locations: Location[] = [
  { id: '1', name: 'Chattagram', level: 'division', parent_id: 'country-bd' },
  { id: '2', name: 'Rajshahi', level: 'division', parent_id: 'country-bd' },
  { id: '3', name: 'Khulna', level: 'division', parent_id: 'country-bd' },
  { id: '4', name: 'Barisal', level: 'division', parent_id: 'country-bd' },
  { id: '5', name: 'Sylhet', level: 'division', parent_id: 'country-bd' },
  { id: '6', name: 'Dhaka', level: 'division', parent_id: 'country-bd' },
  { id: '7', name: 'Rangpur', level: 'division', parent_id: 'country-bd' },
  { id: '8', name: 'Mymensingh', level: 'division', parent_id: 'country-bd' },
  { id: '1', name: 'Comilla', level: 'district', parent_id: '1' },
  { id: '2', name: 'Feni', level: 'district', parent_id: '1' },
  { id: '3', name: 'Brahmanbaria', level: 'district', parent_id: '1' },
  { id: '4', name: 'Rangamati', level: 'district', parent_id: '1' },
  { id: '5', name: 'Noakhali', level: 'district', parent_id: '1' },
  { id: '6', name: 'Chandpur', level: 'district', parent_id: '1' },
  { id: '7', name: 'Lakshmipur', level: 'district', parent_id: '1' },
  { id: '8', name: 'Chattogram', level: 'district', parent_id: '1' },
  { id: '9', name: 'Coxsbazar', level: 'district', parent_id: '1' },
  { id: '10', name: 'Khagrachhari', level: 'district', parent_id: '1' },
  { id: '11', name: 'Bandarban', level: 'district', parent_id: '1' },
  { id: '12', name: 'Sirajganj', level: 'district', parent_id: '2' },
  { id: '13', name: 'Pabna', level: 'district', parent_id: '2' },
  { id: '14', name: 'Bogura', level: 'district', parent_id: '2' },
  { id: '15', name: 'Rajshahi', level: 'district', parent_id: '2' },
  { id: '16', name: 'Natore', level: 'district', parent_id: '2' },
  { id: '17', name: 'Joypurhat', level: 'district', parent_id: '2' },
  { id: '18', name: 'Chapainawabganj', level: 'district', parent_id: '2' },
  { id: '19', name: 'Naogaon', level: 'district', parent_id: '2' },
  { id: '20', name: 'Jashore', level: 'district', parent_id: '3' },
  { id: '21', name: 'Satkhira', level: 'district', parent_id: '3' },
  { id: '22', name: 'Meherpur', level: 'district', parent_id: '3' },
  { id: '23', name: 'Narail', level: 'district', parent_id: '3' },
  { id: '24', name: 'Chuadanga', level: 'district', parent_id: '3' },
  { id: '25', name: 'Kushtia', level: 'district', parent_id: '3' },
  { id: '26', name: 'Magura', level: 'district', parent_id: '3' },
  { id: '27', name: 'Khulna', level: 'district', parent_id: '3' },
  { id: '28', name: 'Bagerhat', level: 'district', parent_id: '3' },
  { id: '29', name: 'Jhenaidah', level: 'district', parent_id: '3' },
  { id: '30', name: 'Jhalakathi', level: 'district', parent_id: '4' },
  { id: '31', name: 'Patuakhali', level: 'district', parent_id: '4' },
  { id: '32', name: 'Pirojpur', level: 'district', parent_id: '4' },
  { id: '33', name: 'Barisal', level: 'district', parent_id: '4' },
  { id: '34', name: 'Bhola', level: 'district', parent_id: '4' },
  { id: '35', name: 'Barguna', level: 'district', parent_id: '4' },
  { id: '36', name: 'Sylhet', level: 'district', parent_id: '5' },
  { id: '37', name: 'Moulvibazar', level: 'district', parent_id: '5' },
  { id: '38', name: 'Habiganj', level: 'district', parent_id: '5' },
  { id: '39', name: 'Sunamganj', level: 'district', parent_id: '5' },
  { id: '40', name: 'Narsingdi', level: 'district', parent_id: '6' },
  { id: '41', name: 'Gazipur', level: 'district', parent_id: '6' },
  { id: '42', name: 'Shariatpur', level: 'district', parent_id: '6' },
  { id: '43', name: 'Narayanganj', level: 'district', parent_id: '6' },
  { id: '44', name: 'Tangail', level: 'district', parent_id: '6' },
  { id: '45', name: 'Kishoreganj', level: 'district', parent_id: '6' },
  { id: '46', name: 'Manikganj', level: 'district', parent_id: '6' },
  { id: '47', name: 'Dhaka', level: 'district', parent_id: '6' },
  { id: '48', name: 'Munshiganj', level: 'district', parent_id: '6' },
  { id: '49', name: 'Rajbari', level: 'district', parent_id: '6' },
  { id: '50', name: 'Madaripur', level: 'district', parent_id: '6' },
  { id: '51', name: 'Gopalganj', level: 'district', parent_id: '6' },
  { id: '52', name: 'Faridpur', level: 'district', parent_id: '6' },
  { id: '53', name: 'Panchagarh', level: 'district', parent_id: '7' },
  { id: '54', name: 'Dinajpur', level: 'district', parent_id: '7' },
  { id: '55', name: 'Lalmonirhat', level: 'district', parent_id: '7' },
  { id: '56', name: 'Nilphamari', level: 'district', parent_id: '7' },
  { id: '57', name: 'Gaibandha', level: 'district', parent_id: '7' },
  { id: '58', name: 'Thakurgaon', level: 'district', parent_id: '7' },
  { id: '59', name: 'Rangpur', level: 'district', parent_id: '7' },
  { id: '60', name: 'Kurigram', level: 'district', parent_id: '7' },
  { id: '61', name: 'Sherpur', level: 'district', parent_id: '8' },
  { id: '62', name: 'Mymensingh', level: 'district', parent_id: '8' },
  { id: '63', name: 'Jamalpur', level: 'district', parent_id: '8' },
  { id: '64', name: 'Netrokona', level: 'district', parent_id: '8' },
  { id: '1', name: 'Debidwar', level: 'upazila', parent_id: '1' },
  { id: '2', name: 'Barura', level: 'upazila', parent_id: '1' },
  { id: '3', name: 'Brahmanpara', level: 'upazila', parent_id: '1' },
  { id: '4', name: 'Chandina', level: 'upazila', parent_id: '1' },
  { id: '5', name: 'Chauddagram', level: 'upazila', parent_id: '1' },
  { id: '6', name: 'Daudkandi', level: 'upazila', parent_id: '1' },
  { id: '7', name: 'Homna', level: 'upazila', parent_id: '1' },
  { id: '8', name: 'Laksam', level: 'upazila', parent_id: '1' },
  { id: '9', name: 'Muradnagar', level: 'upazila', parent_id: '1' },
  { id: '10', name: 'Nangalkot', level: 'upazila', parent_id: '1' },
  { id: '11', name: 'Comilla Sadar', level: 'upazila', parent_id: '1' },
  { id: '12', name: 'Meghna', level: 'upazila', parent_id: '1' },
  { id: '13', name: 'Monohargonj', level: 'upazila', parent_id: '1' },
  { id: '14', name: 'Sadarsouth', level: 'upazila', parent_id: '1' },
  { id: '15', name: 'Titas', level: 'upazila', parent_id: '1' },
  { id: '16', name: 'Burichang', level: 'upazila', parent_id: '1' },
  { id: '17', name: 'Lalmai', level: 'upazila', parent_id: '1' },
  { id: '18', name: 'Chhagalnaiya', level: 'upazila', parent_id: '2' },
  { id: '19', name: 'Feni Sadar', level: 'upazila', parent_id: '2' },
  { id: '20', name: 'Sonagazi', level: 'upazila', parent_id: '2' },
  { id: '21', name: 'Fulgazi', level: 'upazila', parent_id: '2' },
  { id: '22', name: 'Parshuram', level: 'upazila', parent_id: '2' },
  { id: '23', name: 'Daganbhuiyan', level: 'upazila', parent_id: '2' },
  { id: '24', name: 'Brahmanbaria Sadar', level: 'upazila', parent_id: '3' },
  { id: '25', name: 'Kasba', level: 'upazila', parent_id: '3' },
  { id: '26', name: 'Nasirnagar', level: 'upazila', parent_id: '3' },
  { id: '27', name: 'Sarail', level: 'upazila', parent_id: '3' },
  { id: '28', name: 'Ashuganj', level: 'upazila', parent_id: '3' },
  { id: '29', name: 'Akhaura', level: 'upazila', parent_id: '3' },
  { id: '30', name: 'Nabinagar', level: 'upazila', parent_id: '3' },
  { id: '31', name: 'Bancharampur', level: 'upazila', parent_id: '3' },
  { id: '32', name: 'Bijoynagar', level: 'upazila', parent_id: '3' },
  { id: '33', name: 'Rangamati Sadar', level: 'upazila', parent_id: '4' },
  { id: '34', name: 'Kaptai', level: 'upazila', parent_id: '4' },
  { id: '35', name: 'Kawkhali', level: 'upazila', parent_id: '4' },
  { id: '36', name: 'Baghaichari', level: 'upazila', parent_id: '4' },
  { id: '37', name: 'Barkal', level: 'upazila', parent_id: '4' },
  { id: '38', name: 'Langadu', level: 'upazila', parent_id: '4' },
  { id: '39', name: 'Rajasthali', level: 'upazila', parent_id: '4' },
  { id: '40', name: 'Belaichari', level: 'upazila', parent_id: '4' },
  { id: '41', name: 'Juraichari', level: 'upazila', parent_id: '4' },
  { id: '42', name: 'Naniarchar', level: 'upazila', parent_id: '4' },
  { id: '43', name: 'Noakhali Sadar', level: 'upazila', parent_id: '5' },
  { id: '44', name: 'Companiganj', level: 'upazila', parent_id: '5' },
  { id: '45', name: 'Begumganj', level: 'upazila', parent_id: '5' },
  { id: '46', name: 'Hatia', level: 'upazila', parent_id: '5' },
  { id: '47', name: 'Subarnachar', level: 'upazila', parent_id: '5' },
  { id: '48', name: 'Kabirhat', level: 'upazila', parent_id: '5' },
  { id: '49', name: 'Senbug', level: 'upazila', parent_id: '5' },
  { id: '50', name: 'Chatkhil', level: 'upazila', parent_id: '5' },
  { id: '51', name: 'Sonaimori', level: 'upazila', parent_id: '5' },
  { id: '52', name: 'Haimchar', level: 'upazila', parent_id: '6' },
  { id: '53', name: 'Kachua', level: 'upazila', parent_id: '6' },
  { id: '54', name: 'Shahrasti', level: 'upazila', parent_id: '6' },
  { id: '55', name: 'Chandpur Sadar', level: 'upazila', parent_id: '6' },
  { id: '56', name: 'Matlab South', level: 'upazila', parent_id: '6' },
  { id: '57', name: 'Hajiganj', level: 'upazila', parent_id: '6' },
  { id: '58', name: 'Matlab North', level: 'upazila', parent_id: '6' },
  { id: '59', name: 'Faridgonj', level: 'upazila', parent_id: '6' },
  { id: '60', name: 'Lakshmipur Sadar', level: 'upazila', parent_id: '7' },
  { id: '61', name: 'Kamalnagar', level: 'upazila', parent_id: '7' },
  { id: '62', name: 'Raipur', level: 'upazila', parent_id: '7' },
  { id: '63', name: 'Ramgati', level: 'upazila', parent_id: '7' },
  { id: '64', name: 'Ramganj', level: 'upazila', parent_id: '7' },
  { id: '65', name: 'Rangunia', level: 'upazila', parent_id: '8' },
  { id: '66', name: 'Sitakunda', level: 'upazila', parent_id: '8' },
  { id: '67', name: 'Mirsharai', level: 'upazila', parent_id: '8' },
  { id: '68', name: 'Patiya', level: 'upazila', parent_id: '8' },
  { id: '69', name: 'Sandwip', level: 'upazila', parent_id: '8' },
  { id: '70', name: 'Banshkhali', level: 'upazila', parent_id: '8' },
  { id: '71', name: 'Boalkhali', level: 'upazila', parent_id: '8' },
  { id: '72', name: 'Anwara', level: 'upazila', parent_id: '8' },
  { id: '73', name: 'Chandanaish', level: 'upazila', parent_id: '8' },
  { id: '74', name: 'Satkania', level: 'upazila', parent_id: '8' },
  { id: '75', name: 'Lohagara', level: 'upazila', parent_id: '8' },
  { id: '76', name: 'Hathazari', level: 'upazila', parent_id: '8' },
  { id: '77', name: 'Fatikchhari', level: 'upazila', parent_id: '8' },
  { id: '78', name: 'Raozan', level: 'upazila', parent_id: '8' },
  { id: '79', name: 'Karnafuli', level: 'upazila', parent_id: '8' },
  { id: '80', name: 'Coxsbazar Sadar', level: 'upazila', parent_id: '9' },
  { id: '81', name: 'Chakaria', level: 'upazila', parent_id: '9' },
  { id: '82', name: 'Kutubdia', level: 'upazila', parent_id: '9' },
  { id: '83', name: 'Ukhiya', level: 'upazila', parent_id: '9' },
  { id: '84', name: 'Moheshkhali', level: 'upazila', parent_id: '9' },
  { id: '85', name: 'Pekua', level: 'upazila', parent_id: '9' },
  { id: '86', name: 'Ramu', level: 'upazila', parent_id: '9' },
  { id: '87', name: 'Teknaf', level: 'upazila', parent_id: '9' },
  { id: '88', name: 'Khagrachhari Sadar', level: 'upazila', parent_id: '10' },
  { id: '89', name: 'Dighinala', level: 'upazila', parent_id: '10' },
  { id: '90', name: 'Panchari', level: 'upazila', parent_id: '10' },
  { id: '91', name: 'Laxmichhari', level: 'upazila', parent_id: '10' },
  { id: '92', name: 'Mohalchari', level: 'upazila', parent_id: '10' },
  { id: '93', name: 'Manikchari', level: 'upazila', parent_id: '10' },
  { id: '94', name: 'Ramgarh', level: 'upazila', parent_id: '10' },
  { id: '95', name: 'Matiranga', level: 'upazila', parent_id: '10' },
  { id: '96', name: 'Guimara', level: 'upazila', parent_id: '10' },
  { id: '97', name: 'Bandarban Sadar', level: 'upazila', parent_id: '11' },
  { id: '98', name: 'Alikadam', level: 'upazila', parent_id: '11' },
  { id: '99', name: 'Naikhongchhari', level: 'upazila', parent_id: '11' },
  { id: '100', name: 'Rowangchhari', level: 'upazila', parent_id: '11' },
  { id: '101', name: 'Lama', level: 'upazila', parent_id: '11' },
  { id: '102', name: 'Ruma', level: 'upazila', parent_id: '11' },
  { id: '103', name: 'Thanchi', level: 'upazila', parent_id: '11' },
  { id: '104', name: 'Belkuchi', level: 'upazila', parent_id: '12' },
  { id: '105', name: 'Chauhali', level: 'upazila', parent_id: '12' },
  { id: '106', name: 'Kamarkhand', level: 'upazila', parent_id: '12' },
  { id: '107', name: 'Kazipur', level: 'upazila', parent_id: '12' },
  { id: '108', name: 'Raigonj', level: 'upazila', parent_id: '12' },
  { id: '109', name: 'Shahjadpur', level: 'upazila', parent_id: '12' },
  { id: '110', name: 'Sirajganj Sadar', level: 'upazila', parent_id: '12' },
  { id: '111', name: 'Tarash', level: 'upazila', parent_id: '12' },
  { id: '112', name: 'Ullapara', level: 'upazila', parent_id: '12' },
  { id: '113', name: 'Sujanagar', level: 'upazila', parent_id: '13' },
  { id: '114', name: 'Ishurdi', level: 'upazila', parent_id: '13' },
  { id: '115', name: 'Bhangura', level: 'upazila', parent_id: '13' },
  { id: '116', name: 'Pabna Sadar', level: 'upazila', parent_id: '13' },
  { id: '117', name: 'Bera', level: 'upazila', parent_id: '13' },
  { id: '118', name: 'Atghoria', level: 'upazila', parent_id: '13' },
  { id: '119', name: 'Chatmohar', level: 'upazila', parent_id: '13' },
  { id: '120', name: 'Santhia', level: 'upazila', parent_id: '13' },
  { id: '121', name: 'Faridpur', level: 'upazila', parent_id: '13' },
  { id: '122', name: 'Kahaloo', level: 'upazila', parent_id: '14' },
  { id: '123', name: 'Bogra Sadar', level: 'upazila', parent_id: '14' },
  { id: '124', name: 'Shariakandi', level: 'upazila', parent_id: '14' },
  { id: '125', name: 'Shajahanpur', level: 'upazila', parent_id: '14' },
  { id: '126', name: 'Dupchanchia', level: 'upazila', parent_id: '14' },
  { id: '127', name: 'Adamdighi', level: 'upazila', parent_id: '14' },
  { id: '128', name: 'Nondigram', level: 'upazila', parent_id: '14' },
  { id: '129', name: 'Sonatala', level: 'upazila', parent_id: '14' },
  { id: '130', name: 'Dhunot', level: 'upazila', parent_id: '14' },
  { id: '131', name: 'Gabtali', level: 'upazila', parent_id: '14' },
  { id: '132', name: 'Sherpur', level: 'upazila', parent_id: '14' },
  { id: '133', name: 'Shibganj', level: 'upazila', parent_id: '14' },
  { id: '134', name: 'Paba', level: 'upazila', parent_id: '15' },
  { id: '135', name: 'Durgapur', level: 'upazila', parent_id: '15' },
  { id: '136', name: 'Mohonpur', level: 'upazila', parent_id: '15' },
  { id: '137', name: 'Charghat', level: 'upazila', parent_id: '15' },
  { id: '138', name: 'Puthia', level: 'upazila', parent_id: '15' },
  { id: '139', name: 'Bagha', level: 'upazila', parent_id: '15' },
  { id: '140', name: 'Godagari', level: 'upazila', parent_id: '15' },
  { id: '141', name: 'Tanore', level: 'upazila', parent_id: '15' },
  { id: '142', name: 'Bagmara', level: 'upazila', parent_id: '15' },
  { id: '143', name: 'Natore Sadar', level: 'upazila', parent_id: '16' },
  { id: '144', name: 'Singra', level: 'upazila', parent_id: '16' },
  { id: '145', name: 'Baraigram', level: 'upazila', parent_id: '16' },
  { id: '146', name: 'Bagatipara', level: 'upazila', parent_id: '16' },
  { id: '147', name: 'Lalpur', level: 'upazila', parent_id: '16' },
  { id: '148', name: 'Gurudaspur', level: 'upazila', parent_id: '16' },
  { id: '149', name: 'Naldanga', level: 'upazila', parent_id: '16' },
  { id: '150', name: 'Akkelpur', level: 'upazila', parent_id: '17' },
  { id: '151', name: 'Kalai', level: 'upazila', parent_id: '17' },
  { id: '152', name: 'Khetlal', level: 'upazila', parent_id: '17' },
  { id: '153', name: 'Panchbibi', level: 'upazila', parent_id: '17' },
  { id: '154', name: 'Joypurhat Sadar', level: 'upazila', parent_id: '17' },
  { id: '155', name: 'Chapainawabganj Sadar', level: 'upazila', parent_id: '18' },
  { id: '156', name: 'Gomostapur', level: 'upazila', parent_id: '18' },
  { id: '157', name: 'Nachol', level: 'upazila', parent_id: '18' },
  { id: '158', name: 'Bholahat', level: 'upazila', parent_id: '18' },
  { id: '159', name: 'Shibganj', level: 'upazila', parent_id: '18' },
  { id: '160', name: 'Mohadevpur', level: 'upazila', parent_id: '19' },
  { id: '161', name: 'Badalgachi', level: 'upazila', parent_id: '19' },
  { id: '162', name: 'Patnitala', level: 'upazila', parent_id: '19' },
  { id: '163', name: 'Dhamoirhat', level: 'upazila', parent_id: '19' },
  { id: '164', name: 'Niamatpur', level: 'upazila', parent_id: '19' },
  { id: '165', name: 'Manda', level: 'upazila', parent_id: '19' },
  { id: '166', name: 'Atrai', level: 'upazila', parent_id: '19' },
  { id: '167', name: 'Raninagar', level: 'upazila', parent_id: '19' },
  { id: '168', name: 'Naogaon Sadar', level: 'upazila', parent_id: '19' },
  { id: '169', name: 'Porsha', level: 'upazila', parent_id: '19' },
  { id: '170', name: 'Sapahar', level: 'upazila', parent_id: '19' },
  { id: '171', name: 'Manirampur', level: 'upazila', parent_id: '20' },
  { id: '172', name: 'Abhaynagar', level: 'upazila', parent_id: '20' },
  { id: '173', name: 'Bagherpara', level: 'upazila', parent_id: '20' },
  { id: '174', name: 'Chougachha', level: 'upazila', parent_id: '20' },
  { id: '175', name: 'Jhikargacha', level: 'upazila', parent_id: '20' },
  { id: '176', name: 'Keshabpur', level: 'upazila', parent_id: '20' },
  { id: '177', name: 'Jessore Sadar', level: 'upazila', parent_id: '20' },
  { id: '178', name: 'Sharsha', level: 'upazila', parent_id: '20' },
  { id: '179', name: 'Assasuni', level: 'upazila', parent_id: '21' },
  { id: '180', name: 'Debhata', level: 'upazila', parent_id: '21' },
  { id: '181', name: 'Kalaroa', level: 'upazila', parent_id: '21' },
  { id: '182', name: 'Satkhira Sadar', level: 'upazila', parent_id: '21' },
  { id: '183', name: 'Shyamnagar', level: 'upazila', parent_id: '21' },
  { id: '184', name: 'Tala', level: 'upazila', parent_id: '21' },
  { id: '185', name: 'Kaliganj', level: 'upazila', parent_id: '21' },
  { id: '186', name: 'Mujibnagar', level: 'upazila', parent_id: '22' },
  { id: '187', name: 'Meherpur Sadar', level: 'upazila', parent_id: '22' },
  { id: '188', name: 'Gangni', level: 'upazila', parent_id: '22' },
  { id: '189', name: 'Narail Sadar', level: 'upazila', parent_id: '23' },
  { id: '190', name: 'Lohagara', level: 'upazila', parent_id: '23' },
  { id: '191', name: 'Kalia', level: 'upazila', parent_id: '23' },
  { id: '192', name: 'Chuadanga Sadar', level: 'upazila', parent_id: '24' },
  { id: '193', name: 'Alamdanga', level: 'upazila', parent_id: '24' },
  { id: '194', name: 'Damurhuda', level: 'upazila', parent_id: '24' },
  { id: '195', name: 'Jibannagar', level: 'upazila', parent_id: '24' },
  { id: '196', name: 'Kushtia Sadar', level: 'upazila', parent_id: '25' },
  { id: '197', name: 'Kumarkhali', level: 'upazila', parent_id: '25' },
  { id: '198', name: 'Khoksa', level: 'upazila', parent_id: '25' },
  { id: '199', name: 'Mirpur', level: 'upazila', parent_id: '25' },
  { id: '200', name: 'Daulatpur', level: 'upazila', parent_id: '25' },
  { id: '201', name: 'Bheramara', level: 'upazila', parent_id: '25' },
  { id: '202', name: 'Shalikha', level: 'upazila', parent_id: '26' },
  { id: '203', name: 'Sreepur', level: 'upazila', parent_id: '26' },
  { id: '204', name: 'Magura Sadar', level: 'upazila', parent_id: '26' },
  { id: '205', name: 'Mohammadpur', level: 'upazila', parent_id: '26' },
  { id: '206', name: 'Paikgasa', level: 'upazila', parent_id: '27' },
  { id: '207', name: 'Fultola', level: 'upazila', parent_id: '27' },
  { id: '208', name: 'Digholia', level: 'upazila', parent_id: '27' },
  { id: '209', name: 'Rupsha', level: 'upazila', parent_id: '27' },
  { id: '210', name: 'Terokhada', level: 'upazila', parent_id: '27' },
  { id: '211', name: 'Dumuria', level: 'upazila', parent_id: '27' },
  { id: '212', name: 'Botiaghata', level: 'upazila', parent_id: '27' },
  { id: '213', name: 'Dakop', level: 'upazila', parent_id: '27' },
  { id: '214', name: 'Koyra', level: 'upazila', parent_id: '27' },
  { id: '215', name: 'Fakirhat', level: 'upazila', parent_id: '28' },
  { id: '216', name: 'Bagerhat Sadar', level: 'upazila', parent_id: '28' },
  { id: '217', name: 'Mollahat', level: 'upazila', parent_id: '28' },
  { id: '218', name: 'Sarankhola', level: 'upazila', parent_id: '28' },
  { id: '219', name: 'Rampal', level: 'upazila', parent_id: '28' },
  { id: '220', name: 'Morrelganj', level: 'upazila', parent_id: '28' },
  { id: '221', name: 'Kachua', level: 'upazila', parent_id: '28' },
  { id: '222', name: 'Mongla', level: 'upazila', parent_id: '28' },
  { id: '223', name: 'Chitalmari', level: 'upazila', parent_id: '28' },
  { id: '224', name: 'Jhenaidah Sadar', level: 'upazila', parent_id: '29' },
  { id: '225', name: 'Shailkupa', level: 'upazila', parent_id: '29' },
  { id: '226', name: 'Harinakundu', level: 'upazila', parent_id: '29' },
  { id: '227', name: 'Kaliganj', level: 'upazila', parent_id: '29' },
  { id: '228', name: 'Kotchandpur', level: 'upazila', parent_id: '29' },
  { id: '229', name: 'Moheshpur', level: 'upazila', parent_id: '29' },
  { id: '230', name: 'Jhalakathi Sadar', level: 'upazila', parent_id: '30' },
  { id: '231', name: 'Kathalia', level: 'upazila', parent_id: '30' },
  { id: '232', name: 'Nalchity', level: 'upazila', parent_id: '30' },
  { id: '233', name: 'Rajapur', level: 'upazila', parent_id: '30' },
  { id: '234', name: 'Bauphal', level: 'upazila', parent_id: '31' },
  { id: '235', name: 'Patuakhali Sadar', level: 'upazila', parent_id: '31' },
  { id: '236', name: 'Dumki', level: 'upazila', parent_id: '31' },
  { id: '237', name: 'Dashmina', level: 'upazila', parent_id: '31' },
  { id: '238', name: 'Kalapara', level: 'upazila', parent_id: '31' },
  { id: '239', name: 'Mirzaganj', level: 'upazila', parent_id: '31' },
  { id: '240', name: 'Galachipa', level: 'upazila', parent_id: '31' },
  { id: '241', name: 'Rangabali', level: 'upazila', parent_id: '31' },
  { id: '242', name: 'Pirojpur Sadar', level: 'upazila', parent_id: '32' },
  { id: '243', name: 'Nazirpur', level: 'upazila', parent_id: '32' },
  { id: '244', name: 'Kawkhali', level: 'upazila', parent_id: '32' },
  { id: '245', name: 'Zianagar', level: 'upazila', parent_id: '32' },
  { id: '246', name: 'Bhandaria', level: 'upazila', parent_id: '32' },
  { id: '247', name: 'Mathbaria', level: 'upazila', parent_id: '32' },
  { id: '248', name: 'Nesarabad', level: 'upazila', parent_id: '32' },
  { id: '249', name: 'Barisal Sadar', level: 'upazila', parent_id: '33' },
  { id: '250', name: 'Bakerganj', level: 'upazila', parent_id: '33' },
  { id: '251', name: 'Babuganj', level: 'upazila', parent_id: '33' },
  { id: '252', name: 'Wazirpur', level: 'upazila', parent_id: '33' },
  { id: '253', name: 'Banaripara', level: 'upazila', parent_id: '33' },
  { id: '254', name: 'Gournadi', level: 'upazila', parent_id: '33' },
  { id: '255', name: 'Agailjhara', level: 'upazila', parent_id: '33' },
  { id: '256', name: 'Mehendiganj', level: 'upazila', parent_id: '33' },
  { id: '257', name: 'Muladi', level: 'upazila', parent_id: '33' },
  { id: '258', name: 'Hizla', level: 'upazila', parent_id: '33' },
  { id: '259', name: 'Bhola Sadar', level: 'upazila', parent_id: '34' },
  { id: '260', name: 'Borhan Sddin', level: 'upazila', parent_id: '34' },
  { id: '261', name: 'Charfesson', level: 'upazila', parent_id: '34' },
  { id: '262', name: 'Doulatkhan', level: 'upazila', parent_id: '34' },
  { id: '263', name: 'Monpura', level: 'upazila', parent_id: '34' },
  { id: '264', name: 'Tazumuddin', level: 'upazila', parent_id: '34' },
  { id: '265', name: 'Lalmohan', level: 'upazila', parent_id: '34' },
  { id: '266', name: 'Amtali', level: 'upazila', parent_id: '35' },
  { id: '267', name: 'Barguna Sadar', level: 'upazila', parent_id: '35' },
  { id: '268', name: 'Betagi', level: 'upazila', parent_id: '35' },
  { id: '269', name: 'Bamna', level: 'upazila', parent_id: '35' },
  { id: '270', name: 'Pathorghata', level: 'upazila', parent_id: '35' },
  { id: '271', name: 'Taltali', level: 'upazila', parent_id: '35' },
  { id: '272', name: 'Balaganj', level: 'upazila', parent_id: '36' },
  { id: '273', name: 'Beanibazar', level: 'upazila', parent_id: '36' },
  { id: '274', name: 'Bishwanath', level: 'upazila', parent_id: '36' },
  { id: '275', name: 'Companiganj', level: 'upazila', parent_id: '36' },
  { id: '276', name: 'Fenchuganj', level: 'upazila', parent_id: '36' },
  { id: '277', name: 'Golapganj', level: 'upazila', parent_id: '36' },
  { id: '278', name: 'Gowainghat', level: 'upazila', parent_id: '36' },
  { id: '279', name: 'Jaintiapur', level: 'upazila', parent_id: '36' },
  { id: '280', name: 'Kanaighat', level: 'upazila', parent_id: '36' },
  { id: '281', name: 'Sylhet Sadar', level: 'upazila', parent_id: '36' },
  { id: '282', name: 'Zakiganj', level: 'upazila', parent_id: '36' },
  { id: '283', name: 'Dakshinsurma', level: 'upazila', parent_id: '36' },
  { id: '284', name: 'Osmaninagar', level: 'upazila', parent_id: '36' },
  { id: '285', name: 'Barlekha', level: 'upazila', parent_id: '37' },
  { id: '286', name: 'Kamolganj', level: 'upazila', parent_id: '37' },
  { id: '287', name: 'Kulaura', level: 'upazila', parent_id: '37' },
  { id: '288', name: 'Moulvibazar Sadar', level: 'upazila', parent_id: '37' },
  { id: '289', name: 'Rajnagar', level: 'upazila', parent_id: '37' },
  { id: '290', name: 'Sreemangal', level: 'upazila', parent_id: '37' },
  { id: '291', name: 'Juri', level: 'upazila', parent_id: '37' },
  { id: '292', name: 'Nabiganj', level: 'upazila', parent_id: '38' },
  { id: '293', name: 'Bahubal', level: 'upazila', parent_id: '38' },
  { id: '294', name: 'Ajmiriganj', level: 'upazila', parent_id: '38' },
  { id: '295', name: 'Baniachong', level: 'upazila', parent_id: '38' },
  { id: '296', name: 'Lakhai', level: 'upazila', parent_id: '38' },
  { id: '297', name: 'Chunarughat', level: 'upazila', parent_id: '38' },
  { id: '298', name: 'Habiganj Sadar', level: 'upazila', parent_id: '38' },
  { id: '299', name: 'Madhabpur', level: 'upazila', parent_id: '38' },
  { id: '300', name: 'Sunamganj Sadar', level: 'upazila', parent_id: '39' },
  { id: '301', name: 'South Sunamganj', level: 'upazila', parent_id: '39' },
  { id: '302', name: 'Bishwambarpur', level: 'upazila', parent_id: '39' },
  { id: '303', name: 'Chhatak', level: 'upazila', parent_id: '39' },
  { id: '304', name: 'Jagannathpur', level: 'upazila', parent_id: '39' },
  { id: '305', name: 'Dowarabazar', level: 'upazila', parent_id: '39' },
  { id: '306', name: 'Tahirpur', level: 'upazila', parent_id: '39' },
  { id: '307', name: 'Dharmapasha', level: 'upazila', parent_id: '39' },
  { id: '308', name: 'Jamalganj', level: 'upazila', parent_id: '39' },
  { id: '309', name: 'Shalla', level: 'upazila', parent_id: '39' },
  { id: '310', name: 'Derai', level: 'upazila', parent_id: '39' },
  { id: '311', name: 'Belabo', level: 'upazila', parent_id: '40' },
  { id: '312', name: 'Monohardi', level: 'upazila', parent_id: '40' },
  { id: '313', name: 'Narsingdi Sadar', level: 'upazila', parent_id: '40' },
  { id: '314', name: 'Palash', level: 'upazila', parent_id: '40' },
  { id: '315', name: 'Raipura', level: 'upazila', parent_id: '40' },
  { id: '316', name: 'Shibpur', level: 'upazila', parent_id: '40' },
  { id: '317', name: 'Kaliganj', level: 'upazila', parent_id: '41' },
  { id: '318', name: 'Kaliakair', level: 'upazila', parent_id: '41' },
  { id: '319', name: 'Kapasia', level: 'upazila', parent_id: '41' },
  { id: '320', name: 'Gazipur Sadar', level: 'upazila', parent_id: '41' },
  { id: '321', name: 'Sreepur', level: 'upazila', parent_id: '41' },
  { id: '322', name: 'Shariatpur Sadar', level: 'upazila', parent_id: '42' },
  { id: '323', name: 'Naria', level: 'upazila', parent_id: '42' },
  { id: '324', name: 'Zajira', level: 'upazila', parent_id: '42' },
  { id: '325', name: 'Gosairhat', level: 'upazila', parent_id: '42' },
  { id: '326', name: 'Bhedarganj', level: 'upazila', parent_id: '42' },
  { id: '327', name: 'Damudya', level: 'upazila', parent_id: '42' },
  { id: '328', name: 'Araihazar', level: 'upazila', parent_id: '43' },
  { id: '329', name: 'Bandar', level: 'upazila', parent_id: '43' },
  { id: '330', name: 'Narayanganj Sadar', level: 'upazila', parent_id: '43' },
  { id: '331', name: 'Rupganj', level: 'upazila', parent_id: '43' },
  { id: '332', name: 'Sonargaon', level: 'upazila', parent_id: '43' },
  { id: '333', name: 'Basail', level: 'upazila', parent_id: '44' },
  { id: '334', name: 'Bhuapur', level: 'upazila', parent_id: '44' },
  { id: '335', name: 'Delduar', level: 'upazila', parent_id: '44' },
  { id: '336', name: 'Ghatail', level: 'upazila', parent_id: '44' },
  { id: '337', name: 'Gopalpur', level: 'upazila', parent_id: '44' },
  { id: '338', name: 'Madhupur', level: 'upazila', parent_id: '44' },
  { id: '339', name: 'Mirzapur', level: 'upazila', parent_id: '44' },
  { id: '340', name: 'Nagarpur', level: 'upazila', parent_id: '44' },
  { id: '341', name: 'Sakhipur', level: 'upazila', parent_id: '44' },
  { id: '342', name: 'Tangail Sadar', level: 'upazila', parent_id: '44' },
  { id: '343', name: 'Kalihati', level: 'upazila', parent_id: '44' },
  { id: '344', name: 'Dhanbari', level: 'upazila', parent_id: '44' },
  { id: '345', name: 'Itna', level: 'upazila', parent_id: '45' },
  { id: '346', name: 'Katiadi', level: 'upazila', parent_id: '45' },
  { id: '347', name: 'Bhairab', level: 'upazila', parent_id: '45' },
  { id: '348', name: 'Tarail', level: 'upazila', parent_id: '45' },
  { id: '349', name: 'Hossainpur', level: 'upazila', parent_id: '45' },
  { id: '350', name: 'Pakundia', level: 'upazila', parent_id: '45' },
  { id: '351', name: 'Kuliarchar', level: 'upazila', parent_id: '45' },
  { id: '352', name: 'Kishoreganj Sadar', level: 'upazila', parent_id: '45' },
  { id: '353', name: 'Karimgonj', level: 'upazila', parent_id: '45' },
  { id: '354', name: 'Bajitpur', level: 'upazila', parent_id: '45' },
  { id: '355', name: 'Austagram', level: 'upazila', parent_id: '45' },
  { id: '356', name: 'Mithamoin', level: 'upazila', parent_id: '45' },
  { id: '357', name: 'Nikli', level: 'upazila', parent_id: '45' },
  { id: '358', name: 'Harirampur', level: 'upazila', parent_id: '46' },
  { id: '359', name: 'Saturia', level: 'upazila', parent_id: '46' },
  { id: '360', name: 'Manikganj Sadar', level: 'upazila', parent_id: '46' },
  { id: '361', name: 'Gior', level: 'upazila', parent_id: '46' },
  { id: '362', name: 'Shibaloy', level: 'upazila', parent_id: '46' },
  { id: '363', name: 'Doulatpur', level: 'upazila', parent_id: '46' },
  { id: '364', name: 'Singiar', level: 'upazila', parent_id: '46' },
  { id: '365', name: 'Savar', level: 'upazila', parent_id: '47' },
  { id: '366', name: 'Dhamrai', level: 'upazila', parent_id: '47' },
  { id: '367', name: 'Keraniganj', level: 'upazila', parent_id: '47' },
  { id: '368', name: 'Nawabganj', level: 'upazila', parent_id: '47' },
  { id: '369', name: 'Dohar', level: 'upazila', parent_id: '47' },
  { id: '370', name: 'Munshiganj Sadar', level: 'upazila', parent_id: '48' },
  { id: '371', name: 'Sreenagar', level: 'upazila', parent_id: '48' },
  { id: '372', name: 'Sirajdikhan', level: 'upazila', parent_id: '48' },
  { id: '373', name: 'Louhajanj', level: 'upazila', parent_id: '48' },
  { id: '374', name: 'Gajaria', level: 'upazila', parent_id: '48' },
  { id: '375', name: 'Tongibari', level: 'upazila', parent_id: '48' },
  { id: '376', name: 'Rajbari Sadar', level: 'upazila', parent_id: '49' },
  { id: '377', name: 'Goalanda', level: 'upazila', parent_id: '49' },
  { id: '378', name: 'Pangsa', level: 'upazila', parent_id: '49' },
  { id: '379', name: 'Baliakandi', level: 'upazila', parent_id: '49' },
  { id: '380', name: 'Kalukhali', level: 'upazila', parent_id: '49' },
  { id: '381', name: 'Madaripur Sadar', level: 'upazila', parent_id: '50' },
  { id: '382', name: 'Shibchar', level: 'upazila', parent_id: '50' },
  { id: '383', name: 'Kalkini', level: 'upazila', parent_id: '50' },
  { id: '384', name: 'Rajoir', level: 'upazila', parent_id: '50' },
  { id: '385', name: 'Gopalganj Sadar', level: 'upazila', parent_id: '51' },
  { id: '386', name: 'Kashiani', level: 'upazila', parent_id: '51' },
  { id: '387', name: 'Tungipara', level: 'upazila', parent_id: '51' },
  { id: '388', name: 'Kotalipara', level: 'upazila', parent_id: '51' },
  { id: '389', name: 'Muksudpur', level: 'upazila', parent_id: '51' },
  { id: '390', name: 'Faridpur Sadar', level: 'upazila', parent_id: '52' },
  { id: '391', name: 'Alfadanga', level: 'upazila', parent_id: '52' },
  { id: '392', name: 'Boalmari', level: 'upazila', parent_id: '52' },
  { id: '393', name: 'Sadarpur', level: 'upazila', parent_id: '52' },
  { id: '394', name: 'Nagarkanda', level: 'upazila', parent_id: '52' },
  { id: '395', name: 'Bhanga', level: 'upazila', parent_id: '52' },
  { id: '396', name: 'Charbhadrasan', level: 'upazila', parent_id: '52' },
  { id: '397', name: 'Madhukhali', level: 'upazila', parent_id: '52' },
  { id: '398', name: 'Saltha', level: 'upazila', parent_id: '52' },
  { id: '399', name: 'Panchagarh Sadar', level: 'upazila', parent_id: '53' },
  { id: '400', name: 'Debiganj', level: 'upazila', parent_id: '53' },
  { id: '401', name: 'Boda', level: 'upazila', parent_id: '53' },
  { id: '402', name: 'Atwari', level: 'upazila', parent_id: '53' },
  { id: '403', name: 'Tetulia', level: 'upazila', parent_id: '53' },
  { id: '404', name: 'Nawabganj', level: 'upazila', parent_id: '54' },
  { id: '405', name: 'Birganj', level: 'upazila', parent_id: '54' },
  { id: '406', name: 'Ghoraghat', level: 'upazila', parent_id: '54' },
  { id: '407', name: 'Birampur', level: 'upazila', parent_id: '54' },
  { id: '408', name: 'Parbatipur', level: 'upazila', parent_id: '54' },
  { id: '409', name: 'Bochaganj', level: 'upazila', parent_id: '54' },
  { id: '410', name: 'Kaharol', level: 'upazila', parent_id: '54' },
  { id: '411', name: 'Fulbari', level: 'upazila', parent_id: '54' },
  { id: '412', name: 'Dinajpur Sadar', level: 'upazila', parent_id: '54' },
  { id: '413', name: 'Hakimpur', level: 'upazila', parent_id: '54' },
  { id: '414', name: 'Khansama', level: 'upazila', parent_id: '54' },
  { id: '415', name: 'Birol', level: 'upazila', parent_id: '54' },
  { id: '416', name: 'Chirirbandar', level: 'upazila', parent_id: '54' },
  { id: '417', name: 'Lalmonirhat Sadar', level: 'upazila', parent_id: '55' },
  { id: '418', name: 'Kaliganj', level: 'upazila', parent_id: '55' },
  { id: '419', name: 'Hatibandha', level: 'upazila', parent_id: '55' },
  { id: '420', name: 'Patgram', level: 'upazila', parent_id: '55' },
  { id: '421', name: 'Aditmari', level: 'upazila', parent_id: '55' },
  { id: '422', name: 'Syedpur', level: 'upazila', parent_id: '56' },
  { id: '423', name: 'Domar', level: 'upazila', parent_id: '56' },
  { id: '424', name: 'Dimla', level: 'upazila', parent_id: '56' },
  { id: '425', name: 'Jaldhaka', level: 'upazila', parent_id: '56' },
  { id: '426', name: 'Kishorganj', level: 'upazila', parent_id: '56' },
  { id: '427', name: 'Nilphamari Sadar', level: 'upazila', parent_id: '56' },
  { id: '428', name: 'Sadullapur', level: 'upazila', parent_id: '57' },
  { id: '429', name: 'Gaibandha Sadar', level: 'upazila', parent_id: '57' },
  { id: '430', name: 'Palashbari', level: 'upazila', parent_id: '57' },
  { id: '431', name: 'Saghata', level: 'upazila', parent_id: '57' },
  { id: '432', name: 'Gobindaganj', level: 'upazila', parent_id: '57' },
  { id: '433', name: 'Sundarganj', level: 'upazila', parent_id: '57' },
  { id: '434', name: 'Phulchari', level: 'upazila', parent_id: '57' },
  { id: '435', name: 'Thakurgaon Sadar', level: 'upazila', parent_id: '58' },
  { id: '436', name: 'Pirganj', level: 'upazila', parent_id: '58' },
  { id: '437', name: 'Ranisankail', level: 'upazila', parent_id: '58' },
  { id: '438', name: 'Haripur', level: 'upazila', parent_id: '58' },
  { id: '439', name: 'Baliadangi', level: 'upazila', parent_id: '58' },
  { id: '440', name: 'Rangpur Sadar', level: 'upazila', parent_id: '59' },
  { id: '441', name: 'Gangachara', level: 'upazila', parent_id: '59' },
  { id: '442', name: 'Taragonj', level: 'upazila', parent_id: '59' },
  { id: '443', name: 'Badargonj', level: 'upazila', parent_id: '59' },
  { id: '444', name: 'Mithapukur', level: 'upazila', parent_id: '59' },
  { id: '445', name: 'Pirgonj', level: 'upazila', parent_id: '59' },
  { id: '446', name: 'Kaunia', level: 'upazila', parent_id: '59' },
  { id: '447', name: 'Pirgacha', level: 'upazila', parent_id: '59' },
  { id: '448', name: 'Kurigram Sadar', level: 'upazila', parent_id: '60' },
  { id: '449', name: 'Nageshwari', level: 'upazila', parent_id: '60' },
  { id: '450', name: 'Bhurungamari', level: 'upazila', parent_id: '60' },
  { id: '451', name: 'Phulbari', level: 'upazila', parent_id: '60' },
  { id: '452', name: 'Rajarhat', level: 'upazila', parent_id: '60' },
  { id: '453', name: 'Ulipur', level: 'upazila', parent_id: '60' },
  { id: '454', name: 'Chilmari', level: 'upazila', parent_id: '60' },
  { id: '455', name: 'Rowmari', level: 'upazila', parent_id: '60' },
  { id: '456', name: 'Charrajibpur', level: 'upazila', parent_id: '60' },
  { id: '457', name: 'Sherpur Sadar', level: 'upazila', parent_id: '61' },
  { id: '458', name: 'Nalitabari', level: 'upazila', parent_id: '61' },
  { id: '459', name: 'Sreebordi', level: 'upazila', parent_id: '61' },
  { id: '460', name: 'Nokla', level: 'upazila', parent_id: '61' },
  { id: '461', name: 'Jhenaigati', level: 'upazila', parent_id: '61' },
  { id: '462', name: 'Fulbaria', level: 'upazila', parent_id: '62' },
  { id: '463', name: 'Trishal', level: 'upazila', parent_id: '62' },
  { id: '464', name: 'Bhaluka', level: 'upazila', parent_id: '62' },
  { id: '465', name: 'Muktagacha', level: 'upazila', parent_id: '62' },
  { id: '466', name: 'Mymensingh Sadar', level: 'upazila', parent_id: '62' },
  { id: '467', name: 'Dhobaura', level: 'upazila', parent_id: '62' },
  { id: '468', name: 'Phulpur', level: 'upazila', parent_id: '62' },
  { id: '469', name: 'Haluaghat', level: 'upazila', parent_id: '62' },
  { id: '470', name: 'Gouripur', level: 'upazila', parent_id: '62' },
  { id: '471', name: 'Gafargaon', level: 'upazila', parent_id: '62' },
  { id: '472', name: 'Iswarganj', level: 'upazila', parent_id: '62' },
  { id: '473', name: 'Nandail', level: 'upazila', parent_id: '62' },
  { id: '474', name: 'Tarakanda', level: 'upazila', parent_id: '62' },
  { id: '475', name: 'Jamalpur Sadar', level: 'upazila', parent_id: '63' },
  { id: '476', name: 'Melandah', level: 'upazila', parent_id: '63' },
  { id: '477', name: 'Islampur', level: 'upazila', parent_id: '63' },
  { id: '478', name: 'Dewangonj', level: 'upazila', parent_id: '63' },
  { id: '479', name: 'Sarishabari', level: 'upazila', parent_id: '63' },
  { id: '480', name: 'Madarganj', level: 'upazila', parent_id: '63' },
  { id: '481', name: 'Bokshiganj', level: 'upazila', parent_id: '63' },
  { id: '482', name: 'Barhatta', level: 'upazila', parent_id: '64' },
  { id: '483', name: 'Durgapur', level: 'upazila', parent_id: '64' },
  { id: '484', name: 'Kendua', level: 'upazila', parent_id: '64' },
  { id: '485', name: 'Atpara', level: 'upazila', parent_id: '64' },
  { id: '486', name: 'Madan', level: 'upazila', parent_id: '64' },
  { id: '487', name: 'Khaliajuri', level: 'upazila', parent_id: '64' },
  { id: '488', name: 'Kalmakanda', level: 'upazila', parent_id: '64' },
  { id: '489', name: 'Mohongonj', level: 'upazila', parent_id: '64' },
  { id: '490', name: 'Purbadhala', level: 'upazila', parent_id: '64' },
  { id: '491', name: 'Netrokona Sadar', level: 'upazila', parent_id: '64' },
  { id: '492', name: 'Eidgaon', level: 'upazila', parent_id: '9' },
  { id: '493', name: 'Madhyanagar', level: 'upazila', parent_id: '39' },
  { id: '494', name: 'Dasar', level: 'upazila', parent_id: '50' }
];
